-- T01/T02 스키마 (Oracle DDL 의미를 유지, PostgreSQL 호환)

CREATE SCHEMA IF NOT EXISTS sample;

DROP TABLE IF EXISTS sample."T02" CASCADE;
DROP TABLE IF EXISTS sample."T01" CASCADE;

CREATE TABLE sample."T01" (
  "ID" SERIAL PRIMARY KEY,
  "C01" VARCHAR(20),
  "C02" NUMERIC,
  "C03" TIMESTAMP,
  "C04" VARCHAR(10),
  "C05" INTEGER
);

CREATE TABLE sample."T02" (
  "ID" SERIAL PRIMARY KEY,
  "C01" VARCHAR(10),
  "C02" NUMERIC
);


